version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
  catalog.api:
    build:
      context: .
      dockerfile: Catalog/Catalog.Host/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5000
    ports:
      - 5000:5000

networks:
  dockernet:
    external: true